In [ ]:
# Lab03 Numpy Basics By Bir Mahato

In [12]:
# NumPy Basics
import numpy as np

s = np.arange(12)
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
# 1) Show all element of s
import numpy as np
s 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# 2) Show the third element of s
print(s[2])

# 2) Show the last element of s
print(s[-1])

2
11


In [14]:
# 3) Show the third to last element of s
print(s[2:])

# Show the third to seventh element of s
print(s[2:7])


[ 2  3  4  5  6  7  8  9 10 11]
[2 3 4 5 6]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:

# 4) Show the total of s
print(np.sum(s))

# Show the smallest value of s
print(np.min(s))

# Show the average value of s
print(np.mean(s))

# Show the largest value of s
print(np.max(s))

66
0
5.5
11


In [11]:
# 5) if array change values, will s change values too? why?
# show s values
arry = s
arry[1]= -1
print(s)
print(arry)

[ 0 -1  2  3  4  5  6  7  8  9 10 11]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [12]:
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
print(data)
#what is output of ? print(data.shape)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [13]:
#what is output of ?
print(data.shape)

AttributeError: 'list' object has no attribute 'shape'

In [14]:
matrix = np.array(data)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#what is output of ? 
print(matrix.shape)

(3, 3)


In [16]:
# 6)Show the element of first row of second col of matrix
print(matrix[0,1])

# 6)Show the element of second row of first col of matrix
print(matrix[1,0])

2
4


In [18]:
print(matrix)
print("-------")
# 7 )Show all elements of first row in matrix
print(matrix[0])

#  Show all elements of second row in matrix
print(matrix[1])

# Show all elements of last row in matrix
print(matrix[-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------
[1 2 3]
[4 5 6]
[7 8 9]


In [21]:
# 8) Show all elements of first col in matrix
print(matrix[:,0])

# Show all elements of third col in matrix
print(matrix[:,2])

# Show all elements of last col in matrix
print(matrix[:,-1])

[1 4 7]
[3 6 9]
[3 6 9]


In [23]:
print( matrix)
# Show second rows, and second col to last col's elements in matrix
print(matrix[1,1:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]


In [ ]:
[[ 1 -1  3]
 [ 4  5  6]
 [ 7  8  9]]
[5 6

In [24]:
print(matrix)
# 5) Show the total of matrix
print(sum(matrix))
# or we can use
print(np.sum(matrix))
# Show the smallest value of s
print(matrix.min())
# Show the average value of s
print(matrix.mean())

# Show the largest value of s
print(matrix.max())

# The sum of second col
print(matrix[:,1].sum())
#or we can use 
print(np.sum(matrix[:1,1]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
45
1
5.0
9
15
